profile/urls.py
from django.urls import path

from profile import views

app_name = 'profile'

urlpatterns = [
    path('pay', views.process_payment, name='pay'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('api/occurrences', views.api_occurrences, name='api-occurrences'),
    path('receipt/<int:pk>', views.Receipt.as_view(), name='receipt'),
    path('update/<int:pk>', views.ProfileUpdate.as_view(), name='update'),
    path('<int:pk>', views.ProfileView.as_view(), name='view'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

import frontend

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

finances/models.py
from django.db import models


class BankTransaction(models.Model):
    details = models.TextField()
    posting_date = models.DateField()
    description = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=20)
    type = models.TextField()


class TransactionCategory(models.Model):
    name = models.TextField()


class ApprovedTransaction(models.Model):
    transaction_id = models.ForeignKey(BankTransaction, on_delete=models.CASCADE)
    category = models.ForeignKey(TransactionCategory, on_delete=models.CASCADE)
    approval_date = models.DateField(auto_now=True)
    notes = models.TextField()
    contact = models.ForeignKey("profile.Student", on_delete=models.CASCADE, blank=True, null=True)
    document = models.FileField(upload_to="bank/", blank=True, null=True)
    contact_order = models.ForeignKey("profile.Order", on_delete=models.DO_NOTHING, blank=True, null=True)

profile/models.py
from decimal import Decimal

from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Sum, F, Q
from django.urls import reverse
from django.utils import timezone
from schedule.models import Event
from tinymce.models import HTMLField

from profile.managers import StudentManager, OrderLineItemQuerySet, AvailableProductsManager

USMLE_STEP1, USMLE_STEP2CK, USMLE_STEP2CS, USMLE_STEP3, COMLEX_LEVEL1, COMLEX_LEVEL2, COMLEX_LEVEL3, \
SPECIALTY, MED_COACH_A, MED_COACH_B, OTHER, ALL = range(0, 12)

EXAM_CHOICES = (
    (COMLEX_LEVEL1, "COMLEX Level 1"),
    (COMLEX_LEVEL2, "COMLEX Level 2"),
    (COMLEX_LEVEL3, "COMLEX Level 3"),
    (MED_COACH_A, "Medical School Year 1 & 2 Coaching"),
    (MED_COACH_B, "Medical School Year 3 & 4 Coaching"),
    (SPECIALTY, "Specialty Board Certification"),
    (USMLE_STEP1, "USMLE Step 1"),
    (USMLE_STEP2CK, "USMLE Step 2CK"),
    (USMLE_STEP3, "USMLE Step 3"),
    (OTHER, "Other"),
    (ALL, "All"),
)


class Student(AbstractUser):
    MD, DO = range(0, 2)
    DEGREE_CHOICES = (
        (MD, "MD"),
        (DO, "DO"),
    )
    username = None
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateField()
    last_login = models.DateTimeField()
    institution = models.CharField(max_length=255, blank=True, null=True, verbose_name="School Name")
    balance_paid = models.BooleanField(default=False, blank=True, null=True)
    graduation_year = models.IntegerField(
        blank=False,
        null=True,
        help_text="Enter all 4 digits. If you haven't graduated yet, enter the year you expect to graduate.",
        validators=(
            MinValueValidator(1900),
            MaxValueValidator(2050)
        )
    )
    degree = models.IntegerField(choices=DEGREE_CHOICES, blank=False, null=True, help_text="MD or DO")
    exam = models.IntegerField(
        blank=False,
        null=True,
        choices=EXAM_CHOICES,
        help_text="Choose the exam you are preparing for."
    )
    test_date = models.DateField(
        blank=True,
        null=True,
        help_text="Enter the date that you need to complete the test by or the date you are scheduled to take it."
    )
    phone_number = models.CharField(max_length=31, blank=False, null=True)
    marketing_subscription = models.BooleanField(default=True, verbose_name="Agree to receive marketing emails")
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = StudentManager()

    class Meta:
        verbose_name = "Student"
        ordering = ('last_name', )

    @property
    def exam_count(self):
        return self.examscore_set.filter(exam=self.exam).count()

    @property
    def current_balance(self):
        return self.payment_set.all().aggregate(sum=Sum('total'))['sum'] -\
               self.appointment_set.all().aggregate(sum=Sum('charge'))['sum']

    @property
    def ocean_courage_subscription(self):
        class SubscriptionInformation(object):
            expiration = None

            def __init__(s, expiration):
                s.expiration = expiration

            @property
            def is_expired(s):
                return s.expiration < timezone.now().date() if s.expiration else False

        ocs = self.productuser_set.filter(product__name="Ocean Courage Drill Sessions")
        if ocs:
            si = SubscriptionInformation(max([oc.product_end_date for oc in ocs]))
            return si
        return None

    @property
    def can_access_drills(self):
        return self.productuser_set.filter(
            Q(product_end_date__gte=timezone.now().date()) | Q(product_end_date__isnull=True),
            product__name="Ocean Courage Drill Sessions",
        ).exists()

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.date_joined = timezone.now()
            self.last_login = timezone.now()
        return super().save(*args, **kwargs)

    def get_full_name(self):
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        return reverse('profile:view', kwargs={'pk': self.pk})


class Testimonial(models.Model):
    testimonial = HTMLField()
    citation = models.CharField(max_length=255)

    class Meta:
        ordering = ('-pk', )


class ExamScore(models.Model):
    FAIL, PASS = range(0, 2)
    PASS_CHOICES = (
        (PASS, "Pass"),
        (FAIL, "Fail"),
    )
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam = models.IntegerField(choices=EXAM_CHOICES)
    date = models.DateField(default=timezone.now)
    score = models.IntegerField(choices=PASS_CHOICES)

    def __str__(self):
        return f"{self.student} {self.get_exam_display()} ({self.date}): {self.get_score_display()}"


class Appointment(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, blank=True, null=True, on_delete=models.CASCADE)
    zoom_id = models.CharField(max_length=10,  blank=True, null=True, help_text="Just enter the numbers, not the hyphens.")

    def __str__(self):
        return f"{self.event}: {self.zoom_id}; {self.student}"


class Order(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date_paid = models.DateTimeField(default=timezone.now)
    number = models.CharField(max_length=7)
    total = models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)
    in_person_appt_qty = models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='In Person Appointments')
    remote_appt_qty = models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Online Appointments')

    def __str__(self):
        return f"{self.student} ({self.date_paid}): Paid ${self.grand_total}"

    def get_absolute_url(self):
        return reverse('profile:receipt', kwargs={'pk': self.pk})

    @classmethod
    def get_next_number(cls):
        current_year = timezone.now().year
        orders_this_year = cls.objects.filter(date_paid__year=current_year).count() or 0
        return f"{str(current_year)[2:]}-{(orders_this_year + 1):04d}"

    @property
    def grand_total(self):
        return self.orderlineitem_set.aggregate(
            s=Sum(F('charge') * F('qty'), output_field=models.FloatField())
        )['s'] or 0

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = Order.get_next_number()
        if self.student:
            self.student.balanced_paid = False
            self.student.save()
        result = super().save(*args, **kwargs)
        return result


class OrderLineItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    product_start_date = models.DateField(blank=True, null=True)
    product_end_date = models.DateField(blank=True, null=True)
    qty = models.SmallIntegerField(verbose_name="Quantity")
    # since charges may change over time, save in Order
    charge = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Charge (USD)")
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    objects = OrderLineItemQuerySet.as_manager()

    @property
    def total_charge(self):
        return Decimal(self.qty) * self.charge

    def __str__(self):
        return f"{self.product.name} x{self.qty} @ ${self.charge}; {self.order.student} on {self.order.date_paid}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    notes = models.TextField(blank=True, null=True)
    product_duration = models.DurationField(blank=True, null=True)
    account_name = models.CharField(max_length=255)
    # TODO add ability to track all exams for a particular product so that
    #    we can render only the products that a student would find helpful
    #    based on the exam that they are taking
    charge = models.DecimalField(max_digits=6, decimal_places=2)  # track how much this product costs
    owners = models.ManyToManyField('Student', blank=True, related_name="products")
    expiration_date = models.DateField(blank=True, null=True)
    removed = models.BooleanField()

    objects = models.Manager()
    available = AvailableProductsManager()

    def __str__(self):
        return self.name

    @admin.display()
    def qty_ordered(self):
        return OrderLineItem.objects.filter(product=self.pk).count()


class Course(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date_start = models.DateField()
    duration = models.DurationField()
    duration_access = models.DurationField()

    def __str__(self):
        return str(self.product)


class ContentItem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return f"{self.course[:15]} {self.date}: {self.description}"


class AgendaItem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    time_start = models.TimeField()
    time_duration = models.DurationField()
    description = models.TextField()

    def __str__(self):
        return f"{self.course[:15]} {self.time_start} for {self.time_duration}: {self.description}"


class Staff(Student):
    description = models.TextField()
    image_path = models.CharField(max_length=255)


class Quotation(models.Model):
    customer = models.ForeignKey(Student, on_delete=models.CASCADE)
    number = models.CharField(max_length=50)

profile/views.py
import stripe
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, UpdateView

from profile.forms import OrderForm, StudentChangeForm
from profile.models import Order, Student
# from profile.quickbooks import save_invoice
from utils import send_html_email, send_sms


@login_required
def process_payment(request):
    form = OrderForm(request.POST or None, user=request.user)
    if request.POST:
        # Set your secret key: remember to change this to your live secret key in production
        # See your keys here: https://dashboard.stripe.com/account/apikeys
        stripe.api_key = settings.STRIPE_SECRET_API_KEY

        # Get the payment token ID submitted by the form:
        token = request.POST.get('stripeToken')

        try:
            if token and form.is_valid():
                grand_total = form.grand_total
                if grand_total > 0:
                    stripe.Charge.create(
                        amount=int(grand_total * 100),  # stripe amounts are in pennies
                        currency='usd',
                        description='Ocean Ink',
                        source=token,
                        metadata={'student_id': request.user.pk},
                    )
                try:
                    # save_invoice(order)
                    pass
                except:
                    pass
                # send email message after everything is saved
                order = form.save()
                message = render_to_string('email_receipt.html', {'order': order})
                send_html_email(
                    "New Payment", message, ["matthew.pava@gmail.com", "drlepava@gmail.com"]
                )
                send_html_email(
                    "Thank you for your payment.", message, [order.student.email], "matthew.pava@gmail.com"
                )
                products = ', '.join(order.orderlineitem_set.values_list('product__name', flat=True))
                # send_sms.send(f"{order.student} bought ${order.grand_total}: {products}")
                return redirect(reverse('profile:receipt', kwargs={'pk': order.pk}))
        except stripe.error.CardError as e:
            # Since it's a decline, stripe.error.CardError will be caught
            form.card_errors = e.user_message
        except stripe.error.RateLimitError as e:
            # Too many requests made to the API too quickly
            form.card_errors = "Server error: Stripe rate limit reached. Please try again."
        except stripe.error.InvalidRequestError as e:
            # Invalid parameters were supplied to Stripe's API
            print("User: %s" % request.user)
            print("Invalid parameters sent to Stripe. %s" % e)
        except stripe.error.AuthenticationError as e:
            # Authentication with Stripe's API failed
            # (maybe you changed API keys recently)
            print("User: %s" % request.user)
            print("Invalid Stripe API key.")
        except stripe.error.APIConnectionError as e:
            print("User: %s" % request.user)
            print("Network communication with Stripe failed.")
        except stripe.error.StripeError as e:
            # Display a very generic error to the user, and maybe send
            # yourself an email
            print("User: %s" % request.user)
            print("Generic Stripe error: %s" % e)

    return render(request, template_name="pay.html", context={
        'form': form, 'STRIPE_API_KEY': settings.STRIPE_PUBLISHABLE_API_KEY}
    )


class Receipt(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Order
    template_name = "receipt.html"

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object().student


class ProfileView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Student
    template_name = "view.html"

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object()


class ProfileUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Student
    form_class = StudentChangeForm
    template_name = "form.html"
    success_url = reverse_lazy('frontend:schedule')
    extra_context = {'title': "Update Profile"}

    def test_func(self):
        user = self.request.user
        return user.is_superuser or user == self.get_object()

    def get_form_kwargs(self):
        result = super(ProfileUpdate, self).get_form_kwargs()
        result['user'] = self.request.user
        return result

    def get_success_url(self):
        if self.request.user.is_superuser:
            return reverse("staff:student-list")
        return super(ProfileUpdate, self).get_success_url()

profile/templates/basic.html
<table class="table table-striped">
    <tbody>
        {% if student.ocean_courage_subscription %}
            <tr>
                <th class="col-2">Ocean Courage Expiration Date:</th>
                <td>{{ student.ocean_courage_subscription.expiration|date:"SHORT_DATE_FORMAT" }}{% if student.ocean_courage_subscription.is_expired %} (Expired){% endif %}</td>
            </tr>
        {% endif %}
        <tr>
            <th class="col-2">Email:</th>
            <td class="col-10">{{ student.email }}</td>
        </tr>
        <tr>
            <th>Institution:</th>
            <td>{{ student.institution }}</td>
        </tr>
        <tr>
            <th>Phone number:</th>
            <td>{{ student.phone_number }}</td>
        </tr>
        <tr>
            <th>Date joined:</th>
            <td>{{ student.date_joined|date:"SHORT_DATE_FORMAT" }}</td>
        </tr>
        <tr>
            <th>Last login:</th>
            <td>{{ student.last_login|date:"m/d/Y H:i:s" }}</td>
        </tr>
        <tr>
            <th>Graduation year:</th>
            <td>{{ student.graduation_year }}</td>
        </tr>
        <tr>
            <th>Degree:</th>
            <td>{{ student.get_degree_display }}</td>
        </tr>
        <tr>
            <th>Exam:</th>
            <td>{{ student.get_exam_display }}</td>
        </tr>
        <tr>
            <th>Test date:</th>
            <td>{{ student.test_date|date:"SHORT_DATE_FORMAT" }}</td>
        </tr>
    </tbody>
</table>

profile/templates/calendar.html
git{% extends 'base.html' %}
{% load static %}
{% block extracss %}
    <link href="{% static 'vendor/fullcalendar-4.2.0/packages/core/main.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/fullcalendar-4.2.0/packages/daygrid/main.min.css' %}" rel="stylesheet" />
    <link href="{% static 'vendor/fullcalendar-4.2.0/packages/timegrid/main.min.css' %}" rel="stylesheet" />
{% endblock extracss %}
{% block extrajs %}
<!--    <script src="{% static 'vendor/fullcalendar-3.10.0/lib/jquery.min.js' %}"></script>-->
<!--    <script src="{% static 'vendor/fullcalendar-3.10.0/lib/jquery-ui.min.js' %}"></script>-->
    <script src="{% static 'vendor/fullcalendar-4.2.0/packages/core/main.min.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar-4.2.0/packages/daygrid/main.min.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar-4.2.0/packages/timegrid/main.min.js' %}"></script>
{% endblock extrajs %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="card">
            <h1 class="card-header">Ocean Ink Calendar</h1>
            <div class="card-body">
                <div id="calendar"></div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}
{% block finaljs %}
document.addEventListener("DOMContentLoaded", function() {
  var calendarEl = document.getElementById("calendar");
  var calendar = new FullCalendar.Calendar(calendarEl, {
    plugins: [ "interaction", "dayGrid", "timeGrid" ],
    defaultView: "dayGridMonth",
    header: {
      left: "prev,next today",
      center: "title",
      right: "dayGridMonth,timeGridWeek,timeGridDay"
    },
    events: "{% url 'profile:api-occurrences' %}"
  });
  calendar.render();
});
{% endblock finaljs %}

profile/templates/email.html
            <h2 class="card-header">
                <span class="section-heading-upper">Profile for {{ student }}</span>
            </h2>
            {% include 'basic.html' %}

profile/templates/email_oceancourage.html
{% load utility_tags %}
<section class="page-section cta">
    <div class="container">
        <div class="card">
            <h2 class="card-header">
                <span class="section-heading-upper">New Ocean Courage Order! {% if renewal %}This is a renewal!{% endif %}</span>
            </h2>
            <div class="card-body">
                <ul>
                    <li>Order Date: {{ order.date_paid|date:"SHORT_DATE_FORMAT" }}</li>
                    <li>Student: {{ order.student }}</li>
                    {% include 'basic.html' with student=order.student %}
                </ul>
            </div>
        </div>
    </div>
</section>

profile/templates/email_receipt.html
{% load utility_tags %}
<section class="page-section cta">
    <div class="container">
        <div class="card">
            <h2 class="card-header">
                <span class="section-heading-upper">Receipt {{ order.number }}</span>
            </h2>
            <div class="card-body">
                <ul>
                    <li>Student: {{ order.student }}</li>
                    <li>Student email: <a href="mailto:{{ order.student.email }}">{{ order.student.email }}</a></li>
                    <li>Order Date: {{ order.date_paid|date:"m/d/Y H:i:s" }}</li>
                    {% if order.total %} {# change in the future when these fields are converted to OrderLineItem #}
                        <li>Total Paid: {{ order.total|currency }}</li>
                        <li>In Person Appointments: {{ order.in_person_appt_qty }}</li>
                        <li>Online Appointments: {{ order.remote_appt_qty }}</li>
                    {% else %}
                        <li>Total Paid: {{ order.grand_total|currency }}</li>
                        {% for li in order.orderlineitem_set.all %}
                            <li>{{ li.product.name }}: {{ li.qty }} ({{ li.charge|currency }} ea)<br>
                                <strong>Product Notes:</strong>
                                <ul><li>{{ li.product.notes|safe }}</li></ul>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</section>

profile/templates/email_welcome.html
<p>Dear {{ user }}:</p>
<p>
    Thank you so much for choosing Ocean Ink for your tutoring and studying needs.
    If you have any questions about our services, please let us know. Our services
    are conducted by members of our staff. One of our staff will contact you
    to set up your free consultation.
</p>
<p>
    You will want to subscribe to our monthly Ocean Courage drill sessions package
    on the <a href="https://oceanink.net{% url 'profile:pay' %}">pricing page</a>.
    Within 24 hours, you'll be able to access the drills on the website at your
    convenience.
</p>
<p>
    Please check out our <a href="https://www.facebook.com/oceanink1">Facebook</a> page.
</p>
<p>
    Please let us know if you would like to make any appointments. Pricing is available on the
    <a href="https://oceanink.net{% url 'profile:pay' %}">website</a>. Our physical location is in Urbana, Illinois, but
    we utilize the Internet to access any location you may be in.
</p>
<p>
    We are so happy to have you register with OI.  We love to support all of our students wherever they are.
    We hope together we make a better life for everyone.
</p>
<p>
Best wishes,<br>
Ocean Ink Staff
</p>
<p>
MK Le Pava, MD<br>
Course Lecturer<br>
Ocean Ink LLC<br>
tel:760-672-1049<br>
mailto:drlepava@gmail.com
</p>
<p>
Technical/billing questions can be sent to<br>
Matthew Pava<br>
CEO<br>
tel:217-766-4704<br>
mailto:matthew.pava@gmail.com
</p>

profile/templates/product.html
<div class="form-group">
	<label class="requiredField">Product</label>
	{% include "django/forms/widgets/input.html" %}
	<div><strong>{{ product.name }}</strong><br>{{ product.notes|safe }}</div>
</div>

profile/templates/receipt.html
{% extends 'base.html' %}
{% load static utility_tags admin_urls %}
{% block content %}
{% include 'email_receipt.html' %}
{% if user.is_superuser %}<a class="btn btn-danger" href="{% url 'admin:profile_order_delete' order.pk %}">Delete</a>{% endif %}
{% endblock content %}

profile/templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner rounded">
                    {% if user.is_authenticated %}
                        {% with user.appointment_set.upcoming as upcoming %}
                            {% if upcoming %}
                                You have the following appointments scheduled:
                                <ul>
                                    {% for appt in upcoming %}
                                        <li>{{ appt.get_type_display }}: {{ appt.dt|date:"SHORT_DATE_FORMAT" }} for {{ appt.duration }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        {% endwith %}
                    {% endif %}
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">
                            Call or text us to schedule an appointment at (760) 672-1049.
                            All times are in the central time zone.
                        </span>
                    </h2>
<!--                    <p>-->
<!--                        In-person sessions are held at <a href="https://www.lodgic.org/">Lodgic Everyday Community</a>,-->
<!--                        which requires a separate paid membership that you can <a href="https://lodgic.spaces.nexudus.com/en/signup/priceplan/78353150-2c9f-473a-9a98-a13d68d4e33f">register</a> for.-->
<!--                    </p>-->
                    <p>
                        Online Sessions are held via <a href="http://zoom.us">Zoom</a>.
                        You can also check the <a href="https://www.facebook.com/oceanink1">Facebook</a> page.
                    </p>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Sunday
                            <span class="ml-auto">By appointment only</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Monday
                            <span class="ml-auto">
                                5:00 AM to 8:00 PM<br>
                                8:15 AM to 9:00 AM: Morning Cute Questions
                            </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Tuesday
                            <span class="ml-auto">
                                5:00 AM to 8:00 PM<br>
                                8:15 AM to 9:00 AM: Morning Cute Questions
                            </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Wednesday
                            <span class="ml-auto">
                                5:00 AM to 8:00 PM<br>
                                8:15 AM to 9:00 AM: Morning Cute Questions
                            </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Thursday
                            <span class="ml-auto">
                                5:00 AM to 8:00 PM<br>
                                8:15 AM to 9:00 AM: Morning Cute Questions
                            </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Friday
                            <span class="ml-auto">
                                5:00 AM to 4:00 PM<br>
                                8:15 AM to 9:00 AM: Morning Cute Questions
                            </span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Saturday
                            <span class="ml-auto">Closed</span>
                        </li>
                    </ul>
<!--                    <div>-->
<!--                        Additionally, Ocean Ink is not open on these dates:-->
<!--                        <ul>-->
<!--                            <li>Monday, February 15, 2021</li>-->
<!--                            <li>Friday, April 2, 2021</li>-->
<!--                            <li>Friday, May 28, 2021</li>-->
<!--                            <li>Monday, May 31, 2021</li>-->
<!--                            <li>Monday, July 5, 2021</li>-->
<!--                            <li>Friday, September 3, 2021</li>-->
<!--                            <li>Monday, September 6, 2021</li>-->
<!--                            <li>Thursday, November 25, 2021</li>-->
<!--                            <li>Friday, November 26, 2021</li>-->
<!--                            <li>Thursday, December 23, 2021</li>-->
<!--                            <li>Friday, December 24, 2021</li>-->
<!--                            <li>Thursday, December 30, 2021</li>-->
<!--                            <li>Friday, December 31, 2021</li>-->
<!--                        </ul>-->
<!--                    </div>-->
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

profile/templates/view.html
{% extends 'base.html' %}
{% load static utility_tags %}
{% block content %}
<section class="page-section cta">
    <div class="container">
        <div class="card">
            <h2 class="card-header">
                <span class="section-heading-upper">Profile for {{ student }}</span>
            </h2>
            {% include 'basic.html' %}
            <br>
            {% if student.order_set.exists %}
                <h2 class="card-header">Receipts</h2>
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th class="col-2">Date</th>
                            <th class="col-8">Receipt Number</th>
                            <th class="col-2">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in student.order_set.all %}
                            <tr>
                                <td>{{ order.date_paid|date:"m/d/Y H:i:s"  }}</td>
                                <td><a href="{{ order.get_absolute_url }}">{{ order.number }}</a></td>
                                {% if order.total %}
                                    <td>{{ order.total|currency }}</td>
                                {% else %}
                                    <td>{{ order.grand_total|currency }}</td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <div class="form-actions ml-2 mb-2">
                <a class="btn btn-primary" href="{% url 'profile:update' student.pk %}">Update</a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}