drill/urls.py
from django.urls import path

from drill import views

app_name = "drill"

urlpatterns = [
    path('', views.TopicList.as_view(), name="topics"),
    path('<int:pk>', views.TopicDetail.as_view(), name="questions"),
    path('track/<int:pk>', views.TrackDrill.as_view(), name="drill-track"),
]

frontend/urls.py
from django.urls import path

from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('testimonials', views.TestimonialsView.as_view(), name='testimonials'),
    path('services', views.ServicesView.as_view(), name='services'),
    path('resources', views.ResourcesView.as_view(), name='resources'),
    path('schedule', views.ScheduleView.as_view(), name='schedule'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('legal/privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('legal/terms', views.TermsView.as_view(), name='terms'),
    path('legal/disclaimer', views.DisclaimerView.as_view(), name='disclaimer'),
    path('legal/return-policy', views.ReturnPolicyView.as_view(), name='return-policy'),
]

profile/urls.py
from django.urls import path

from profile import views

app_name = 'profile'

urlpatterns = [
    path('pay', views.process_payment, name='pay'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('api/occurrences', views.api_occurrences, name='api-occurrences'),
    path('receipt/<int:pk>', views.Receipt.as_view(), name='receipt'),
    path('update/<int:pk>', views.ProfileUpdate.as_view(), name='update'),
    path('<int:pk>', views.ProfileView.as_view(), name='view'),
]

staff/urls.py
from django.urls import path

from staff import views

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='staff-index'),
    path('students', views.StudentListView.as_view(), name='student-list'),
    path('orders', views.OrderLineItemListView.as_view(), name='orderlineitem-list'),
    path('ocean-courage', views.OceanCourageSubscribersView.as_view(), name='ocean-courage-list'),
    path('err', views.ThrowError.as_view(), name='throw-error'),
    path('contract', views.SignTerms.as_view(), name='contract'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

import frontend

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% include 'section_about.html' %}
    {% include 'section_staff.html' %}
{% endblock content %}

templates/base.html
{% load static compress tz utility_tags %}
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}USMLE/COMLEX Resources - Ocean Ink{% endblock %}</title>
    <!-- Favicon data -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static '/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static '/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static '/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static '/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static '/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static '/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static '/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static '/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    {% compress css %}
      <!-- Bootstrap core CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/business-casual.min.css' %}" rel="stylesheet">
      {% block extracss %}{% endblock extracss %}
    {% endcompress css %}
    <!-- JavaScript Files -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-141228836-1">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-141228836-1');
    </script>
    {% compress js %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      {% block extrajs %}{% endblock extrajs %}
    {% endcompress js %}
      <script src="https://js.stripe.com/v3/"></script>
  </head>
  <body class="d-flex flex-column h-100{% block bodyClass%}{% endblock %}">
    {% block visibleHeader %}
    {% block facebookPlugin %}{% endblock facebookPlugin %}
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Ocean Ink</span>
      <span class="site-heading-lower">USMLE/COMLEX<br>Resources</span>
    </h1>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">Ocean Ink</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item{% if request.resolver_match.url_name == 'index' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:index' %}">Home
                {% if request.resolver_match.url_name == 'index' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'resources' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:resources' %}">Resources
                {% if request.resolver_match.url_name == 'resources' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'schedule' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:schedule' %}">Schedule
                {% if request.resolver_match.url_name == 'schedule' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'pay' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'profile:pay' %}">Pricing
                {% if request.resolver_match.url_name == 'pay' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'profile:view' pk=user.pk %}">Hi, {{ user.first_name }}! &raquo;
                  {% if request.resolver_match.url_name == 'view' %}<span class="sr-only">(current)</span>{% endif %}
                </a>
              </li>
              <li class="nav-item{% if request.resolver_match.url_name == 'account_logout' %} active{% endif %} px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'account_logout' %}">Sign Out
                  {% if request.resolver_match.url_name == 'account_logout' %}<span class="sr-only">(current)</span>{% endif %}
                </a>
              </li>
              {% if perms.profile.view_student or user|has_group:"oceancouragegroup" or user.is_superuser %}
                <li class="nav-item{% if request.resolver_match.url_name == 'staff' %} active{% endif %} px-lg-4">
                  <a class="nav-link text-uppercase text-expanded" href="{% url 'staff:staff-index' %}">Staff
                    {% if request.resolver_match.url_name == 'staff-index' %}<span class="sr-only">(current)</span>{% endif %}
                  </a>
                </li>
              {% endif %}
              {% if user.can_access_drills %}
              <li class="nav-item{% if request.resolver_match.url_name == 'topics' %} active{% endif %} px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'drill:topics' %}">Drills
                  {% if request.resolver_match.url_name == 'topics' %}<span class="sr-only">(current)</span>{% endif %}
                </a>
              </li>
              {% endif %}
            {% else %}
              <li class="nav-item{% if request.resolver_match.url_name == 'account_login' %} active{% endif %} px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'account_login' %}">Sign In
                  {% if request.resolver_match.url_name == 'account_login' %}<span class="sr-only">(current)</span>{% endif %}
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% comment %}
      {% if occurrences %}
        {% for occurrence in occurrences %}
          {% if occurrence.event.appointment.zoom_id and occurrence.end > now and not occurrence.event.appointment.student_id %}
            {% if now >= occurrence.start|minutes_ago:10 %}
              {% if user.is_authenticated %}
                <section class="alert alert-primary text-center">
                  {{ occurrence.title }} is happening now!  You can <a href="{% url 'profile:pay' %}">subscribe</a> to the
                  Ocean Courage package to have access to by the next session.
                  You are also welcome to join us in person at <a href="https://www.lodgic.org/">Lodgic Everyday Community</a>
                  after paying the Lodgic - Ocean Ink membership fee.
                </section>
              {% else %}
                <section class="alert alert-primary text-center">
                  {{ occurrence.title }} is happening now for all subscribed students. <a href="{% url 'account_login' %}">Sign in</a> or <a href="{% url 'account_signup' %}">register</a> now!
                </section>
              {% endif %}
            {% endif %}
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endcomment %}
    {% endblock visibleHeader %}
    <main role="main" class="flex-shrink-0">
      {% block content %}
      {% endblock content %}
    </main>
    <footer class="footer mt-auto py-3 text-faded text-center">
      <div class="container">
        <p class="m-0 small">Copyright &copy; Ocean Ink LLC {{ now|date:"Y" }} | <a href="{% url 'frontend:about' %}">About Us</a> | <a href="{% url 'frontend:privacy-policy' %}">Privacy Policy</a> | <a href="{% url 'frontend:terms' %}">Terms of Use</a> | <a href="{% url 'frontend:disclaimer' %}">Disclaimer</a> | <a href="{% url 'frontend:return-policy' %}">Return Policy</a></p>
      </div>
    </footer>
    {% compress js %}
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% endcompress js %}
    <script>{% block final_js %}{% endblock final_js %}</script>
      <script>
        // jQuery plugin to prevent double submission of forms
        jQuery.fn.preventDoubleSubmission = function() {
          $(this).on("submit",function(e){
            var $form = $(this);
            if ($form.data("submitted") === true) {
              // Previously submitted - don't submit again
              e.preventDefault();
            } else {
              // Mark it so that the next submit can be ignored
              $form.data("submitted", true);
              var $submit = $form.find("input[type=submit]");
              $submit.data("label", $submit.val()).attr("disabled", true).addClass("disabled").val("Loading...");
            }
          });
          // Keep chainability
          return this;
        };
        $("form").preventDoubleSubmission();
      </script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <section class="page-section clearfix">
    <div class="container">
        <div class="row">
      <div class="intro col-9">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'img/intro.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Ocean Ink USMLE/COMLEX Resources</span>
            <span class="section-heading-lower">We Help You Study</span>
          </h2>
          <p class="mb-3">
            We will work with you to help you develop a study plan and provide one-on-one tutoring.
          </p>
          <div class="intro-button mx-auto">
            <a class="btn btn-primary btn-xl" href="{% if user.is_authenticated %}{% url 'frontend:schedule' %}{% else %}{% url 'account_signup' %}{% endif %}">Work With Us Today!</a>
          </div>
        </div>
      </div>
        <div class="intro col-3">
            <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Foceanink1&tabs=timeline&width=340&height=500&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId=806336309714344" width="340" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>        </div>
      </div>
    </div>
  </section>
  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Our Promise</span>
              <span class="section-heading-lower">To You</span>
            </h2>
            <p class="mb-0">
              We are dedicated to helping you succeed in your endeavors to pass your board exams.
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% include 'section_testimonials.html' %}
{% endblock content %}

templates/resources.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'section_face.html' %}
{% endblock content %}

templates/section_about.html
{% load static %}
<section class="page-section clearfix">
    <div class="container">
        <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'img/about.jpg' %}" alt="">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Help for Those Who Need It</span>
                            <span class="section-heading-lower">About Our Program</span>
                        </h2>
                        <p>
                            Established in 2018 by Dr. MK Le Pava, our program is designed to
                            help medical students and medical professionals in the ever-evolving
                            field of medicine.
                        </p>
                        <p class="mb-0">
                            We know that as we work together, you will improve
                            your test scores and increase
                            your chances of success in the medical field.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/section_face.html
{% load static %}
<section class="page-section clearfix">
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-4">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'img/exam.jpg' %}" alt="">
            </div>
            <div class="bg-faded p-5 mx-auto rounded col-12 col-lg-8">
                <h2 class="section-heading mb-0">
                    <span class="section-heading-lower">The FACE Protocol</span>
                    <span class="section-heading-upper">Test-taking Skills</span>
                </h2><br>
                <p>
                    <strong>FOCUS:</strong> Cover the answers. Read the last sentence of the vignette.  Take a
                    few seconds to understand the author’s question and what you are looking for.
                    Define if the question is a specific/direct question or analytical/indirect question.
                </p>
                <p>
                    <strong>ANALYZE:</strong> Start to read from the beginning of the vignette.  Keep reminding yourself
                    what you are looking for as you read. If it is a direct question, stop at any time
                    you see a specific clue for you answer. If it is an indirect question, you must
                    finish the vignette.
                </p>
                <p>
                    <strong>CONFIDENCE:</strong> Answer the author’s question.  For Step 2/3 tests, you must give your
                    diagnosis in all cases.
                </p>
                <p>
                    <strong>EXECUTE:</strong> Scan through the answer options, execute your choice, which is the closest
                    meaning to match your answer.  When in doubt, repeat FACE.  After the second time,
                    choose choice C if you cannot eliminate any answers, or choose the bottom option if you
                    cross out any options.
                </p>
            </div>
        </div>
    </div>
</section>

templates/section_staff.html
{% load static %}
<section class="page-section clearfix">
    <div class="container">
        <div class="about-heading-content">
            <div class="row">
                <div class="col-xl-9 col-lg-10 mx-auto">
                    <div class="bg-faded rounded p-5">
                        <h2 class="section-heading mb-4">
                            <span class="section-heading-upper">Our Staff</span>
                            <span class="section-heading-lower">We're Here to Help</span>
                        </h2>
                        <div class="row mb-2">
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/mklepava.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                MK Le Pava, MD<br>
                                Founder
                            </p>
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/matthewpava.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Matthew Pava, BS<br>
                                CEO
                            </p>
                        </div>
                        <div class="row mb-2">
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/no-image.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                My-Khanh "Lee" Le, PharmD<br>
                                Pharmacology Education Advisor<br>
                                Continuing Medical Education Coordinator
                            </p>
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/rhodagottfried.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Rhoda Gottfried, MD<br>
                                Educational Advisor for Psychiatry
                            </p>
                        </div>
                        <div class="row mb-2">
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/shantpezeshkian.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Shant Pezeshkian, DO<br>
                                PGY-1 Candidate<br>
                                Osteopathic Medicine Team Leader &amp; Instructor
                            </p>
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/priyashah.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Priya Shah, DO<br>
                                Internal Medicine PGY-1 Candidate<br>
                                Osteopathic Medicine Instructor &amp; Textbook Editor
                            </p>
                        </div>
                        <div class="row mb-2">
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/no-image.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Rushabh H. Shah, MD<br>
                                Internal Medicine PGY-1<br>
                                Educational Consultant
                            </p>
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/no-image.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Thaddeus Boucree, MD, DDS<br>
                                The Institute for Advanced Reconstruction<br>
                                Educational Advisor for Surgery
                            </p>
                        </div>
                        <div class="row mb-2">
                            <p class="col-lg-2 col-6 text-right">
                                <img src="{% static 'img/staff/no-image.jpg' %}" alt="">
                            </p>
                            <p class="col-lg-4 col-6">
                                Huan Jimmy Ngo, BS<br>
                                Computer Engineer
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/section_testimonials.html
<section id="testimonials" class="page-section clearfix carousel slide carousel-fade" data-ride="carousel">
    <div class="container bg-faded rounded pb-5">
        <h1 class="text-center py-5">Testimonials</h1>
        <div class="carousel-inner">
            {% for t in testimonial_list %}
                <blockquote class="blockquote carousel-item{% if forloop.first %} active{% endif %}">
                    {{ t.testimonial|safe }}
                    <footer class="blockquote-footer">
                        {{ t.citation }}
                    </footer>
                </blockquote>
            {% endfor %}
            <a class="carousel-control carousel-control-prev" href="#testimonials" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control carousel-control-next" href="#testimonials" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>

templates/testimonials.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="page-section clearfix">
    <div class="container bg-faded">
        <blockquote class="blockquote">
            <p class="mb-0">
                "I came to know Dr. Le Pava over a long and grueling three months. I was told I would be kicked out of
                medical school if I didn't pass my boards. I had already been a non-traditional student in terms of
                timeline, and I was frightened, hopeless, broken, and everything I shouldn't be when attempting to
                study. I was so embarrassed that I didn't even tell my parents, friends, or family that I was embarking
                on this journey in the middle of the country where I knew no one. For three months, I didn't see a
                single familiar face--I was alone. Initially, I didn't believe that another prep program would help me,
                because really, how are they any different? Little did I know, I was wrong. Not only did Dr. Le Pava
                teach me the knowledge I needed, she taught me how to approach questions in a way I never knew, how to
                study the material, developed personalized plans for me, drilled me, and scheduled me to take practice
                tests strategically that would prepare and desensitize me to the fear and pressure that loomed around
                test day for me. My immense fear, self-doubt, and feelings of inadequacy were eating at me every day,
                and throughout it all she believed in me and pushed me. She cared for me as her own daughter, and told
                me I could persevere through this from day one. Dr. Le Pava knew when I was ready to take the exam
                because she recognized when my confidence was built, when my thinking process was clear, and when I was
                able to concentrate fully on myself. I was able to succeed with her help. I went from a 381 to a 613, a
                232 point increase--something that I thought was IMPOSSIBLE. Every time I talk about these dark times,
                I can't speak of them without my heart being overcome in appreciation for Dr. Le Pava. She was and is
                like a mother to me. She revived me and taught me how to prove myself through COMLEX, and I have the
                opportunity to become a doctor today because of her."
            </p>
            <footer class="blockquote-footer">
                Prya Shah, DO, COMLEX Level 2
            </footer>
        </blockquote>
    </div>
</section>
{% endblock content %}