frontend/urls.py
from django.urls import path

from frontend import views

app_name = 'frontend'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', views.AboutView.as_view(), name='about'),
    path('testimonials', views.TestimonialsView.as_view(), name='testimonials'),
    path('services', views.ServicesView.as_view(), name='services'),
    path('resources', views.ResourcesView.as_view(), name='resources'),
    path('schedule', views.ScheduleView.as_view(), name='schedule'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('legal/privacy-policy', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    path('legal/terms', views.TermsView.as_view(), name='terms'),
    path('legal/disclaimer', views.DisclaimerView.as_view(), name='disclaimer'),
    path('legal/return-policy', views.ReturnPolicyView.as_view(), name='return-policy'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

import frontend

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

frontend/views.py
from django.views.generic import TemplateView, ListView

from profile.models import Testimonial


class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['testimonial_list'] = Testimonial.objects.all()
        return context


class ResourcesView(TemplateView):
    template_name = "resources.html"


class AboutView(TemplateView):
    template_name = "about.html"


class TestimonialsView(ListView):
    template_name = "section_testimonials.html"
    model = Testimonial


class ServicesView(TemplateView):
    template_name = "services.html"


class ScheduleView(TemplateView):
    template_name = "schedule.html"


class PrivacyPolicyView(TemplateView):
    template_name = "legal/privacy_policy.html"


class TermsView(TemplateView):
    template_name = "legal/terms.html"


class DisclaimerView(TemplateView):
    template_name = "legal/disclaimer.html"


class ReturnPolicyView(TemplateView):
    template_name = "legal/return_policy.html"

frontend/templates/base.html
{% load static compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}USMLE/Comlex Resources - Oceans Ink{% endblock %}</title>
    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    {% compress css %}
      <!-- Bootstrap core CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href="{% static 'css/business-casual.min.css' %}" rel="stylesheet">
      {% block extracss %}{% endblock extracss %}
    {% endcompress css %}
    <!-- JavaScript Files -->
    {% compress js %}
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      {% block extrajs %}{% endblock extrajs %}
    {% endcompress js %}
  </head>
  <body>
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Oceans Ink</span>
      <span class="site-heading-lower">USMLE/Comlex<br>Resources</span>
    </h1>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">USMLE/Comlex Resources</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item{% if request.resolver_match.url_name == 'index' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:index' %}">Home
                {% if request.resolver_match.url_name == 'index' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'about' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:about' %}">About
                {% if request.resolver_match.url_name == 'about' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'services' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:services' %}">Services
                {% if request.resolver_match.url_name == 'services' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'schedule' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'frontend:schedule' %}">Schedule
                {% if request.resolver_match.url_name == 'schedule' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
            <li class="nav-item{% if request.resolver_match.url_name == 'register' or request.resolver_match.url_name == 'create' %} active{% endif %} px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'profile:register' %}">Register
                {% if request.resolver_match.url_name == 'register' or request.resolver_match.url_name == 'create' %}<span class="sr-only">(current)</span>{% endif %}
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
      <section class="page-section clearfix">
        <div class="container">
          <div class="intro">
            <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'img/intro.jpg' %}" alt="">
            <div class="intro-text left-0 text-center bg-faded p-5 rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Oceans Ink USMLE/Comlex Resources</span>
                <span class="section-heading-lower">We Help You Study</span>
              </h2>
              <p class="mb-3">
                We will work with you to help you develop a study plan and provide one-on-one tutoring.
              </p>
              <div class="intro-button mx-auto">
                <a class="btn btn-primary btn-xl" href="{% url 'profile:register' %}">Work With Us Today!</a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section class="page-section cta">
        <div class="container">
          <div class="row">
            <div class="col-xl-9 mx-auto">
              <div class="cta-inner text-center rounded">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Our Promise</span>
                  <span class="section-heading-lower">To You</span>
                </h2>
                <p class="mb-0">
                  We are dedicated to helping you succeed in your endeavors to pass your board exams.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    {% endblock content %}
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0 small">Copyright &copy; Oceans Ink, Inc. 2018</p>
      </div>
    </footer>
    {% compress js %}
      <!-- Bootstrap core JavaScript -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% endcompress js %}
  </body>
</html>

frontend/templates/pricing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">General Schedule in Central Time Zone</span>
                        <span class="section-heading-lower">We're Open</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Sunday
                            <span class="ml-auto">Closed</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Monday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Tuesday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Wednesday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Thursday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Friday
                            <span class="ml-auto">5:00 AM to 4:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Saturday
                            <span class="ml-auto">Closed</span>
                        </li>
                    </ul>
                    <p class="address mb-5">
                        <em>
                            <strong>2001 S Mattis Ave</strong>
                            <br>
                            Champaign, Illinois
                        </em>
                    </p>
                    <p class="mb-0">
                        <small>
                            <em>Call Anytime</em>
                        </small>
                        <br>
                        (760) 672-1049
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% include 'section_about.html' %}
{% endblock content %}

frontend/templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="page-section cta">
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <div class="cta-inner text-center rounded">
                    <h2 class="section-heading mb-5">
                        <span class="section-heading-upper">General Schedule in Central Time Zone</span>
                        <span class="section-heading-lower">We're Open</span>
                    </h2>
                    <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Sunday
                            <span class="ml-auto">Closed</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Monday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Tuesday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Wednesday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Thursday
                            <span class="ml-auto">5:00 AM to 8:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Friday
                            <span class="ml-auto">5:00 AM to 4:00 PM</span>
                        </li>
                        <li class="list-unstyled-item list-hours-item d-flex">
                            Saturday
                            <span class="ml-auto">Closed</span>
                        </li>
                    </ul>
                    <p class="address mb-5">
                        <em>
                            <strong>2001 S Mattis Ave</strong>
                            <br>
                            Champaign, Illinois
                        </em>
                    </p>
                    <p class="mb-0">
                        <small>
                            <em>Call Anytime</em>
                        </small>
                        <br>
                        (760) 672-1049
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% include 'section_about.html' %}
{% endblock content %}

frontend/templates/services.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex ml-auto rounded">
                    <h2 class="section-heading mb-0">
                        <span class="section-heading-upper">Tutoring</span>
                        <span class="section-heading-lower">One-on-one Sessions</span>
                    </h2>
                </div>
            </div>
            <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'img/products-01.jpg' %}" alt="">
            <div class="product-item-description d-flex mr-auto">
                <div class="bg-faded p-5 rounded">
                    <p class="mb-0">
                        Every time we work with you in a one-on-one tutoring session,
                        you will feel better about your
                        career path, and you will have a plan
                        of action that will improve your score.
                        Currently, we can meet
                        in-person or remotely via Microsoft Skype.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% comment %}
<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex mr-auto rounded">
                    <h2 class="section-heading mb-0">
                        <span class="section-heading-upper">Lectures</span>
                        <span class="section-heading-lower">Group Learning Session</span>
                    </h2>
                </div>
            </div>
            <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'img/products-02.jpg' %}" alt="">
            <div class="product-item-description d-flex ml-auto">
                <div class="bg-faded p-5 rounded">
                    <p class="mb-0">
                        Lectures give you the opportunity to learn material in a more formal fashion.
                        Each lecture is chock-full of information that will help you
                        succeed in passing your exam and improve your knowledge for use
                        in the field.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="page-section">
    <div class="container">
        <div class="product-item">
            <div class="product-item-title d-flex">
                <div class="bg-faded p-5 d-flex ml-auto rounded">
                    <h2 class="section-heading mb-0">
                        <span class="section-heading-upper">Question Bank</span>
                        <span class="section-heading-lower">Self-study</span>
                    </h2>
                </div>
            </div>
            <img class="product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{% static 'img/products-03.jpg' %}" alt="">
            <div class="product-item-description d-flex mr-auto">
                <div class="bg-faded p-5 rounded">
                    <p class="mb-0">
                        By utilizing our question bank, you have the opportunity to
                        experience the test without actually taking the test.  Experience
                        is the best teacher.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endcomment %}
{% endblock content %}