profile/urls.py
from django.urls import path

from profile import views

app_name = 'profile'

urlpatterns = [
    path('pay', views.process_payment, name='pay'),
    path('calendar', views.CalendarView.as_view(), name='calendar'),
    path('api/occurrences', views.api_occurrences, name='api-occurrences'),
    path('receipt/<int:pk>', views.Receipt.as_view(), name='receipt'),
    path('update/<int:pk>', views.ProfileUpdate.as_view(), name='update'),
    path('<int:pk>', views.ProfileView.as_view(), name='view'),
]

staff/urls.py
from django.urls import path

from staff import views

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='staff-index'),
    path('students', views.StudentListView.as_view(), name='student-list'),
    path('orders', views.OrderLineItemListView.as_view(), name='orderlineitem-list'),
    path('ocean-courage', views.OceanCourageSubscribersView.as_view(), name='ocean-courage-list'),
    path('err', views.ThrowError.as_view(), name='throw-error'),
    path('contract', views.SignTerms.as_view(), name='contract'),
]

urls.py
from django.contrib import admin
from django.urls import path, include

import frontend

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

profile/models.py
from decimal import Decimal

from django.contrib import admin
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Sum, F, Q
from django.urls import reverse
from django.utils import timezone
from schedule.models import Event
from tinymce.models import HTMLField

from profile.managers import StudentManager, OrderLineItemQuerySet, AvailableProductsManager

USMLE_STEP1, USMLE_STEP2CK, USMLE_STEP2CS, USMLE_STEP3, COMLEX_LEVEL1, COMLEX_LEVEL2, COMLEX_LEVEL3, \
SPECIALTY, MED_COACH_A, MED_COACH_B, OTHER, ALL = range(0, 12)

EXAM_CHOICES = (
    (COMLEX_LEVEL1, "COMLEX Level 1"),
    (COMLEX_LEVEL2, "COMLEX Level 2"),
    (COMLEX_LEVEL3, "COMLEX Level 3"),
    (MED_COACH_A, "Medical School Year 1 & 2 Coaching"),
    (MED_COACH_B, "Medical School Year 3 & 4 Coaching"),
    (SPECIALTY, "Specialty Board Certification"),
    (USMLE_STEP1, "USMLE Step 1"),
    (USMLE_STEP2CK, "USMLE Step 2CK"),
    (USMLE_STEP3, "USMLE Step 3"),
    (OTHER, "Other"),
    (ALL, "All"),
)


class Student(AbstractUser):
    MD, DO = range(0, 2)
    DEGREE_CHOICES = (
        (MD, "MD"),
        (DO, "DO"),
    )
    username = None
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateField()
    last_login = models.DateTimeField()
    institution = models.CharField(max_length=255, blank=True, null=True, verbose_name="School Name")
    balance_paid = models.BooleanField(default=False, blank=True, null=True)
    graduation_year = models.IntegerField(
        blank=False,
        null=True,
        help_text="Enter all 4 digits. If you haven't graduated yet, enter the year you expect to graduate.",
        validators=(
            MinValueValidator(1900),
            MaxValueValidator(2050)
        )
    )
    degree = models.IntegerField(choices=DEGREE_CHOICES, blank=False, null=True, help_text="MD or DO")
    exam = models.IntegerField(
        blank=False,
        null=True,
        choices=EXAM_CHOICES,
        help_text="Choose the exam you are preparing for."
    )
    test_date = models.DateField(
        blank=True,
        null=True,
        help_text="Enter the date that you need to complete the test by or the date you are scheduled to take it."
    )
    phone_number = models.CharField(max_length=31, blank=False, null=True)
    marketing_subscription = models.BooleanField(default=True, verbose_name="Agree to receive marketing emails")
    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']
    objects = StudentManager()

    class Meta:
        verbose_name = "Student"
        ordering = ('last_name', )

    @property
    def exam_count(self):
        return self.examscore_set.filter(exam=self.exam).count()

    @property
    def current_balance(self):
        return self.payment_set.all().aggregate(sum=Sum('total'))['sum'] -\
               self.appointment_set.all().aggregate(sum=Sum('charge'))['sum']

    @property
    def ocean_courage_subscription(self):
        class SubscriptionInformation(object):
            expiration = None

            def __init__(s, expiration):
                s.expiration = expiration

            @property
            def is_expired(s):
                return s.expiration < timezone.now().date() if s.expiration else False

        ocs = self.productuser_set.filter(product__name="Ocean Courage Drill Sessions")
        if ocs:
            si = SubscriptionInformation(max([oc.product_end_date for oc in ocs]))
            return si
        return None

    @property
    def can_access_drills(self):
        return self.productuser_set.filter(
            Q(product_end_date__gte=timezone.now().date()) | Q(product_end_date__isnull=True),
            product__name="Ocean Courage Drill Sessions",
        ).exists()

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.date_joined = timezone.now()
            self.last_login = timezone.now()
        return super().save(*args, **kwargs)

    def get_full_name(self):
        return f"{self.last_name}, {self.first_name}"

    def get_absolute_url(self):
        return reverse('profile:view', kwargs={'pk': self.pk})


class Testimonial(models.Model):
    testimonial = HTMLField()
    citation = models.CharField(max_length=255)

    class Meta:
        ordering = ('-pk', )


class ExamScore(models.Model):
    FAIL, PASS = range(0, 2)
    PASS_CHOICES = (
        (PASS, "Pass"),
        (FAIL, "Fail"),
    )
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    exam = models.IntegerField(choices=EXAM_CHOICES)
    date = models.DateField(default=timezone.now)
    score = models.IntegerField(choices=PASS_CHOICES)

    def __str__(self):
        return f"{self.student} {self.get_exam_display()} ({self.date}): {self.get_score_display()}"


class Appointment(models.Model):
    event = models.OneToOneField(Event, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, blank=True, null=True, on_delete=models.CASCADE)
    zoom_id = models.CharField(max_length=10,  blank=True, null=True, help_text="Just enter the numbers, not the hyphens.")

    def __str__(self):
        return f"{self.event}: {self.zoom_id}; {self.student}"


class Order(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    date_paid = models.DateTimeField(default=timezone.now)
    number = models.CharField(max_length=7)
    total = models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)
    in_person_appt_qty = models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='In Person Appointments')
    remote_appt_qty = models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Online Appointments')

    def __str__(self):
        return f"{self.student} ({self.date_paid}): Paid ${self.grand_total}"

    def get_absolute_url(self):
        return reverse('profile:receipt', kwargs={'pk': self.pk})

    @classmethod
    def get_next_number(cls):
        current_year = timezone.now().year
        orders_this_year = cls.objects.filter(date_paid__year=current_year).count() or 0
        return f"{str(current_year)[2:]}-{(orders_this_year + 1):04d}"

    @property
    def grand_total(self):
        return self.orderlineitem_set.aggregate(
            s=Sum(F('charge') * F('qty'), output_field=models.FloatField())
        )['s'] or 0

    def save(self, *args, **kwargs):
        if not self.number:
            self.number = Order.get_next_number()
        if self.student:
            self.student.balanced_paid = False
            self.student.save()
        result = super().save(*args, **kwargs)
        return result


class OrderLineItem(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    product_start_date = models.DateField(blank=True, null=True)
    product_end_date = models.DateField(blank=True, null=True)
    qty = models.SmallIntegerField(verbose_name="Quantity")
    # since charges may change over time, save in Order
    charge = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="Charge (USD)")
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    objects = OrderLineItemQuerySet.as_manager()

    @property
    def total_charge(self):
        return Decimal(self.qty) * self.charge

    def __str__(self):
        return f"{self.product.name} x{self.qty} @ ${self.charge}; {self.order.student} on {self.order.date_paid}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    notes = models.TextField(blank=True, null=True)
    product_duration = models.DurationField(blank=True, null=True)
    account_name = models.CharField(max_length=255)
    # TODO add ability to track all exams for a particular product so that
    #    we can render only the products that a student would find helpful
    #    based on the exam that they are taking
    charge = models.DecimalField(max_digits=6, decimal_places=2)  # track how much this product costs
    owners = models.ManyToManyField('Student', blank=True, related_name="products")
    expiration_date = models.DateField(blank=True, null=True)
    removed = models.BooleanField()

    objects = models.Manager()
    available = AvailableProductsManager()

    def __str__(self):
        return self.name

    @admin.display()
    def qty_ordered(self):
        return OrderLineItem.objects.filter(product=self.pk).count()


class Course(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date_start = models.DateField()
    duration = models.DurationField()
    duration_access = models.DurationField()

    def __str__(self):
        return str(self.product)


class ContentItem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return f"{self.course[:15]} {self.date}: {self.description}"


class AgendaItem(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    time_start = models.TimeField()
    time_duration = models.DurationField()
    description = models.TextField()

    def __str__(self):
        return f"{self.course[:15]} {self.time_start} for {self.time_duration}: {self.description}"


class Staff(Student):
    description = models.TextField()
    image_path = models.CharField(max_length=255)


class Quotation(models.Model):
    customer = models.ForeignKey(Student, on_delete=models.CASCADE)
    number = models.CharField(max_length=50)

staff/models.py
from django.db import models

from tinymce.models import HTMLField

from profile.models import Student


class IndependentContractorTerms(models.Model):
    document = HTMLField()
    date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-date', )

    def __str__(self):
        return f"{self.date} - {self.document.replace('<p>', '')[:20]}..."


class ElectronicSignature(models.Model):
    staff_member = models.ForeignKey(Student, on_delete=models.CASCADE)
    initials = models.CharField(max_length=5)
    date = models.DateField()
    document = models.ForeignKey(IndependentContractorTerms, on_delete=models.CASCADE)

    class Meta:
        ordering = ('-date', )

    def __str__(self):
        return f"{self.initials} - {self.date} - {self.staff_member}"

staff/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import FieldError, PermissionDenied
from django.db.models import Case, When, Max, F, Q, IntegerField
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, CreateView
from django.views.generic.base import TemplateView, RedirectView

from profile.models import Student, Appointment, OrderLineItem
from staff.models import ElectronicSignature, IndependentContractorTerms
from utils import divide_chunks


class IndexView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.groups.filter(name="oceancouragegroup").exists():
            return reverse("staff:ocean-courage-list")
        elif self.request.user.groups.filter(name="instructorgroup").exists() or self.request.user.is_superuser:
            return reverse("staff:student-list")
        raise PermissionDenied


class StudentListView(PermissionRequiredMixin, ListView):
    model = Student
    template_name = "staff/student_list.html"
    permission_required = ['profile.view_student']

    def get_queryset(self):
        order_by = self.request.GET.get('ordering')
        with_balance = self.request.GET.get("with_balance")
        q = super().get_queryset().filter(is_staff=False)
        if order_by:
            try:
                q = q.order_by(order_by)
            except FieldError:  # if ordering isn't an actual field
                pass
        if (with_balance and with_balance.lower() == "true") or with_balance is None:
            q = q.filter(balance_paid=False)
        return q

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['marketing_list_chunks'] = divide_chunks(self.get_queryset().filter(marketing_subscription=True), 90)
        return context


class OrderLineItemListView(PermissionRequiredMixin, ListView):
    model = OrderLineItem
    template_name = "staff/orderlineitem_list.html"
    permission_required = ['profile.view_orderlineitem']
    ordering = ('-order__date_paid', )

    def get_queryset(self):
        order_by = self.request.GET.get('ordering')
        q = super().get_queryset()
        if order_by:
            try:
                q = q.order_by(order_by)
            except FieldError:  # if ordering isn't an actual field
                pass
        return q


class AppointmentCreateView(PermissionRequiredMixin, CreateView):
    model = Appointment
    template_name = "appointment.html"
    permission_required = ["profile.create_appointment"]
    form_class = None


class OceanCourageSubscribersView(PermissionRequiredMixin, ListView):
    model = Student
    template_name = "staff/oceancourage_list.html"

    def has_permission(self):
        # you must have a staff account and the student must be a subscriber
        # to the Ocean Courage package
        return self.request.user.groups.filter(name="oceancouragegroup").exists() or self.request.user.is_superuser

    def get_queryset(self):
        order_by = self.request.GET.get('ordering')
        q = super().get_queryset().filter(
            productuser__product_end_date__gte=timezone.now().date(),
            productuser__product__name="Ocean Courage Drill Sessions"
        ).annotate(
            last_purchase_date=Max('order__date_paid')
        )

        if order_by:
            if 'expiration' in order_by:
                sorted_q = sorted(
                    q, key=lambda d: d.ocean_courage_subscription.expiration,
                    reverse=True if '-expiration' in order_by else False
                )
                cases = [When(pk=record.pk, then=sort_order) for sort_order, record in enumerate(sorted_q)]
                q = q.annotate(sort_order=Case(*cases, output_field=IntegerField())).order_by('sort_order')
            else:
                try:
                    q = q.order_by(order_by)
                except FieldError:  # if ordering isn't an actual field
                    pass
        return q


class ThrowError(LoginRequiredMixin, UserPassesTestMixin, TemplateView):
    def test_func(self):
        user = self.request.user
        return user.is_superuser

    def get_context_data(self, **kwargs):
        raise ValueError("Error purposefully generated.")


class SignTerms(PermissionRequiredMixin, CreateView):
    model = ElectronicSignature
    template_name = 'staff/sign_terms.html'
    fields = ['document', 'staff_member', 'date', 'initials']
    success_url = reverse_lazy('frontend:index')

    def has_permission(self):
        # you must have a staff account and the student must be a subscriber
        # to the Ocean Courage package
        return self.request.user.groups.filter(name="oceancouragegroup").exists() or self.request.user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['document'] = IndependentContractorTerms.objects.first()
        context['signature'] = not ElectronicSignature.objects.filter(
            staff_member=self.request.user, document=context['document']
        ).exists()
        return context

staff/templates/staff/oceancourage_list.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="card">
            <h1 class="card-header">Ocean Courage Drill Sessions Subscribers</h1>
            <h5 class="card-header">Emails list</h5>
            <p class="card-body">
                {% for student in student_list %}
                    {% if not student.ocean_courage_subscription.is_expired %}
                        {{ student.email }}{% if not forloop.last %}; {% endif %}
                    {% endif %}
                {% endfor %}
            </p>
        </div>
    </div>
</section>
<section class="page-section">
    <div class="container">
        <div class="card">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="d-flex">
                            <th class="col-4">Student <a href="{% url 'staff:ocean-courage-list' %}?ordering=-last_name">&darr;</a> <a href="{% url 'staff:ocean-courage-list' %}?ordering=last_name">&uarr;</a></th>
                            <th class="col-1">Exam <a href="{% url 'staff:ocean-courage-list' %}?ordering=-exam">&darr;</a> <a href="{% url 'staff:ocean-courage-list' %}?ordering=exam">&uarr;</a></th>
                            <th class="col-3">Email <a href="{% url 'staff:ocean-courage-list' %}?ordering=-email">&darr;</a> <a href="{% url 'staff:ocean-courage-list' %}?ordering=email">&uarr;</a></th>
                            <th class="col-2">Purchase Date <a href="{% url 'staff:ocean-courage-list' %}?ordering=-last_purchase_date">&darr;</a> <a href="{% url 'staff:ocean-courage-list' %}?ordering=last_purchase_date">&uarr;</a></th>
                            <th class="col-2">Expiration Date <a href="{% url 'staff:ocean-courage-list' %}?ordering=-expiration">&darr;</a> <a href="{% url 'staff:ocean-courage-list' %}?ordering=expiration">&uarr;</a></th>
                        </tr>
                        <tr>
                            <th colspan="5">Current Subscriptions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in student_list %}
                            {% if not student.ocean_courage_subscription.is_expired %}
                                <tr class="d-flex">
                                    <td class="col-4">{% if user.is_superuser %}<a href="{{ student.get_absolute_url }}">{% endif %}{{ student }}{% if user.is_superuser %}</a>{% endif %}</td>
                                    <td class="col-1">{% if student.get_exam_display|slice:":6" == "USMLE " or student.get_exam_display|slice:":7" == "COMLEX " %}{{ student.get_exam_display.split|slice:"1:"|join:" " }}{% else %}{{ student.get_exam_display }}{% endif %}</td>
                                    <td class="col-3"><a href="mailto:{{ student.email }}">{{ student.email }}</a></td>
                                    <td class="col-2">{{ student.last_purchase_date|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td class="col-2">{{ student.ocean_courage_subscription.expiration|date:"SHORT_DATE_FORMAT" }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                    <thead>
                        <tr class="d-flex">
                            <th colspan="5" class="col-12">Expired Subscriptions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in student_list %}
                            {% if student.ocean_courage_subscription.is_expired %}
                                <tr class="d-flex">
                                    <td class="col-4">{% if user.is_superuser %}<a href="{{ student.get_absolute_url }}">{% endif %}{{ student.first_name }} {{ student.last_name }}{% if user.is_superuser %}</a>{% endif %}</td>
                                    <td class="col-1">{% if student.get_exam_display|slice:":6" == "USMLE " or student.get_exam_display|slice:":7" == "COMLEX " %}{{ student.get_exam_display.split|slice:"1:"|join:" " }}{% else %}{{ student.get_exam_display }}{% endif %}</td>
                                    <td class="col-3"><a href="mailto:{{ student.email }}">{{ student.email }}</a></td>
                                    <td class="col-2">{{ student.last_purchase_date|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td class="col-2">{{ student.ocean_courage_subscription.expiration|date:"SHORT_DATE_FORMAT" }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

staff/templates/staff/orderlineitem_list.html
{% extends 'base.html' %}
{% load static crispy_forms_tags utility_tags %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="card">
            <h1 class="card-header">Receipt List</h1>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="d-flex">
                            <th class="col-2">Date <a href="{% url 'staff:orderlineitem-list' %}?ordering=-order__date_paid">&darr;</a> <a href="{% url 'staff:orderlineitem-list' %}?ordering=order__date_paid">&uarr;</a></th>
                            <th class="col-3">Student <a href="{% url 'staff:orderlineitem-list' %}?ordering=-order__student">&darr;</a> <a href="{% url 'staff:orderlineitem-list' %}?ordering=order__student">&uarr;</a></th>
                            <th class="col-4">Product <a href="{% url 'staff:orderlineitem-list' %}?ordering=-product__name">&darr;</a> <a href="{% url 'staff:orderlineitem-list' %}?ordering=product__name">&uarr;</a></th>
                            <th class="col-1">Qty <a href="{% url 'staff:orderlineitem-list' %}?ordering=-qty">&darr;</a> <a href="{% url 'staff:orderlineitem-list' %}?ordering=qty">&uarr;</a></th>
                            <th class="col-2">Cost<a href="{% url 'staff:orderlineitem-list' %}?ordering=-charge">&darr;</a> <a href="{% url 'staff:orderlineitem-list' %}?ordering=charge">&uarr;</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for oli in orderlineitem_list %}
                            <tr class="d-flex">
                                <td class="col-2">{% if user.is_superuser %}<a href="{{ oli.order.get_absolute_url }}">{% endif %}{{ oli.order.date_paid|date:"SHORT_DATE_FORMAT" }}{% if user.is_superuser %}</a>{% endif %}</td>
                                <td class="col-3">{% if user.is_superuser %}<a href="{{ oli.order.student.get_absolute_url }}">{% endif %}{{ oli.order.student }}{% if user.is_superuser %}</a>{% endif %}</td>
                                <td class="col-4">{{ oli.product.name }}</td>
                                <td class="col-1">{{ oli.qty }}</td>
                                <td class="col-2">{{ oli.charge|currency }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

staff/templates/staff/sign_terms.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="card">
            <h1 class="card-header">Independent Contractor Terms</h1>
            <h5 class="card-header">(last updated {{ document.date|date:"SHORT_DATE_FORMAT" }})</h5>
            <div class="card-body">
                {{ document.document|safe }}
            </div>
            <h5 class="card-header">Electronic Signature</h5>
            <div class="card-body">
                {% if signature.exists %}
                    You already signed this document on {{ signature.date|date:"SHORT_DATE_FORMAT" }}.
                {% else %}
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="document" value="{{ document.pk }}" />
                        <input type="hidden" name="staff_member" value="{{ request.user.pk }}" />
                        <div class="form-group">
                            <div class="help-block mb-2">
                                {{ request.user.first_name }} {{ request.user.last_name }}, by adding your initials,
                                you agree that your initials will be the
                                electronic representation of your signature whenever you use it.
                                You also understand that recipients of this electronic
                                document will be able to see your initials and email address.
                            </div>
                            <input class="form-control" type="text" name="initials"/>
                        </div>
                        <div class="form-group">
                            <label>Date *</label>
                            <input class="form-control" type="date" name="date" value="{% now 'Y-m-d' %}"/>
                        </div>
                        <div class="form-group">
                            <input class="form-control btn btn-success col-3" type="submit"/>
                        </div>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

staff/templates/staff/student_list.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block content %}
<section class="page-section">
    <div class="container">
        <div class="card">
            <h1 class="card-header"><a href="{% url 'staff:ocean-courage-list' %}" class="btn btn-default">View Ocean Courage Subscribers</a> <a href="{% url 'staff:orderlineitem-list' %}" class="btn btn-default">View Orders</a></h1>
            <h1 class="card-header">Student List</h1>
            <div><a href="{% url 'staff:student-list' %}?with_balance=False">Show All Students</a></div>
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="d-flex">
                            <th class="col-1">ID <a href="{% url 'staff:student-list' %}?ordering=-pk">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=pk">&uarr;</a></th>
                            <th class="col-2">Student <a href="{% url 'staff:student-list' %}?ordering=-last_name">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=last_name">&uarr;</a></th>
                            <th class="col-1">Degree <a href="{% url 'staff:student-list' %}?ordering=-degree">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=degree">&uarr;</a></th>
                            <th class="col-1">Exam <a href="{% url 'staff:student-list' %}?ordering=-exam">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=exam">&uarr;</a></th>
                            <th class="col-2">Exam Date <a href="{% url 'staff:student-list' %}?ordering=-test_date">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=test_date">&uarr;</a></th>
                            <th class="col-2">Phone <a href="{% url 'staff:student-list' %}?ordering=-phone_number">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=phone_number">&uarr;</a></th>
                            <th class="col-3">Email <a href="{% url 'staff:student-list' %}?ordering=-email">&darr;</a> <a href="{% url 'staff:student-list' %}?ordering=email">&uarr;</a></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for student in student_list %}
                            <tr class="d-flex">
                                <td class="col-1">{% if user.is_superuser %}<a href="{% url 'profile:update' pk=student.pk %}">{% endif %}{{ student.pk }}{% if user.is_superuser %}</a>{% endif %}</td>
                                <td class="col-2">{% if user.is_superuser %}<a href="{{ student.get_absolute_url }}">{% endif %}{{ student }}{% if user.is_superuser %}</a>{% endif %}{% if student.institution %}<br>{{ student.institution }}{% endif %}</td>
                                <td class="col-1">{{ student.get_degree_display }}</td>
                                <td class="col-1">{% if student.get_exam_display|slice:":6" == "USMLE " or student.get_exam_display|slice:":7" == "COMLEX " %}{{ student.get_exam_display.split|slice:"1:"|join:" " }}{% else %}{{ student.get_exam_display }}{% endif %}</td>
                                <td class="col-2">{{ student.test_date|default_if_none:"" }}</td>
                                <td class="col-2">{{ student.phone_number }}</td>
                                <td class="col-3"><a href="mailto:{{ student.email }}">{{ student.email }}</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <h5 class="card-header">Marketing Emails list</h5>
                {% for chunk in marketing_list_chunks %}
                    <p class="card-body">
                        {% for student in chunk %}
                            {{ student.email }}{% if not forloop.last %}; {% endif %}
                        {% endfor %}
                    </p>
                {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}